kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: whoami-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`whoami.luigi.ovh`)
      kind: Rule
      services:
        - name: whoami-service
          port: 80
  tls:
    secretName: luigi.ovh
    namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service

spec:
  ports:
    - name: web
      port: 80
  selector:
    app: whoami
