apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: auth-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: traefik
type: kubernetes.io/basic-auth
data:
  username: "bHVpZ2k="
  password: "czNjcjN0"
