ports:
  web:
    port: 8000
    protocol: TCP
  websecure:
    port: 8443
    protocol: TCP
    tls:
      enabled: true
      certResolver: ""
      secretName: luigi.ovh
      domains: []
  traefik:
    port: 8080
    exposedPort: 8080
    targetPort: traefik
    protocol: TCP

api:
  dashboard: true  # Make sure the dashboard is enabled
  insecure: false
