ports:
  web:
    port: 8000
    protocol: TCP
  websecure:
    port: 8443
    protocol: TCP
    tls:
      enabled: true
      certResolver: ""
      secretName: luigi.ovh
      domains: []
  traefik:
    port: 8080
    exposedPort: 8080
    targetPort: traefik
    protocol: TCP

api:
  dashboard: true  # Make sure the dashboard is enabled
  insecure: false

rbac:
  namespaced: false

ingressRoute:
  dashboard:
    enabled: true 
    matchRule: Host(`traefik.luigi.ovh`)
    # -- The internal service used for the dashboard ingressRoute
    services:
      - name: api@internal
        kind: TraefikService
    # -- Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
    # By default, it's using traefik entrypoint, which is not exposed.
    # /!\ Do not expose your dashboard without any protection over the internet /!\
    entryPoints: [websecure]
    # -- Additional ingressRoute middlewares (e.g. for authentication)
    middlewares: 
      - name: basic-auth
        namespace: traefik
    # -- TLS options (e.g. secret containing certificate)
    tls: 
      secretName: luigi.ovh
