apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: luigi.ovh
  namespace: traefik
spec:
  dnsNames:
    - "*.luigi.ovh"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: luigi.ovh
